;;;Copyright (c) 2013 Wilfredo Velázquez-Rodríguez
;;;
;;;This software is provided 'as-is', without any express or implied
;;;warranty. In no event will the authors be held liable for any damages
;;;arising from the use of this software.
;;;
;;;Permission is granted to anyone to use this software for any purpose,
;;;including commercial applications, and to alter it and redistribute
;;;it freely, subject to the following restrictions:
;;;
;;;1. The origin of this software must not be misrepresented; you must not
;;;   claim that you wrote the original software. If you use this software
;;;   in a product, an acknowledgment in the product documentation would
;;;   be appreciated but is not required.
;;;
;;;2. Altered source versions must be plainly marked as such, and must not
;;;   be misrepresented as being the original software.
;;;
;;;3. This notice may not be removed or altered from any source distribution.

(defpackage #:win32
  (:use #:cffi #:cl)
  (:shadow
   #:atom
   #:boolean
   #:byte
   #:char
   #:float)
  (:export
   #:+win32-string-encoding+

   #:char
   #:uchar
   #:wchar

   #:int
   #:int-ptr
   #:int8
   #:int16
   #:int32
   #:int64

   #:uint
   #:uint-ptr
   #:uint8
   #:uint16
   #:uint32
   #:uint64

   #:long
   #:longlong
   #:long-ptr
   #:long32
   #:long64

   #:ulong
   #:ulonglong
   #:ulong-ptr
   #:ulong32
   #:ulong64

   #:short
   #:ushort

   #:byte
   #:word
   #:dword
   #:dwordlong
   #:dword-ptr
   #:dword32
   #:dword64
   #:qword

   #:bool
   #:boolean

   #:tbyte
   #:tchar

   #:float

   #:size-t
   #:ssize-t

   #:lpcstr
   #:lpcwstr
   #:lpstr
   #:lpwstr
   #:pcstr
   #:pcwstr
   #:pstr
   #:pwstr

   #:handle

   #:atom
   #:half-ptr
   #:uhalf-ptr
   #:colorref
   #:haccel
   #:hbitmap
   #:hbrush
   #:hcolorspace
   #:hconv
   #:hconvlist
   #:hcursor
   #:hdc
   #:hddedata
   #:hdesk
   #:hdrop
   #:hdwp
   #:henhmetafile
   #:hfile
   #:hfont
   #:hgdiobj
   #:hglobal
   #:hhook
   #:hicon
   #:hinstance
   #:hkey
   #:hkl
   #:hlocal
   #:hmenu
   #:hmetafile
   #:hmodule
   #:hmonitor
   #:hpalette
   #:hpen
   #:hresult
   #:hrgn
   #:hrsrc
   #:hsz
   #:hwinsta
   #:hwnd
   #:langid
   #:lcid
   #:lgrpid
   #:lparam
   #:lpctstr
   #:lptstr
   #:lresult
   #:pctstr
   #:ptstr
   #:sc-handle
   #:sc-lock
   #:service-status-handle
   #:usn
   #:wparam

   #:hdevinfo

   #:+create-new+
   #:+create-always+
   #:+open-existing+
   #:+open-always+
   #:+truncate-existing+

   #:+pfd-type-rgba+
   #:+pfd-type-colorindex+

   #:+pfd-main-plane+
   #:+pfd-overlay-plane+
   #:+pfd-underlay-plane+

   #:+pfd-doublebuffer+
   #:+pfd-stereo+
   #:+pfd-draw-to-window+
   #:+pfd-draw-to-bitmap+
   #:+pfd-support-gdi+
   #:+pfd-support-opengl+
   #:+pfd-generic-format+
   #:+pfd-need-palette+
   #:+pfd-need-system-palette+
   #:+pfd-swap-exchange+
   #:+pfd-swap-copy+
   #:+pfd-swap-layer-buffers+
   #:+pfd-generic-accelerated+
   #:+pfd-support-directdraw+
   #:+pfd-direct3d-accelerated+
   #:+pfd-support-composition+
   #:+pfd-depth-dontcare+
   #:+pfd-doublebuffer-dontcare+
   #:+pfd-stereo-dontcare+

   ;;Window Styles
   #:+ws-overlapped+
   #:+ws-popup+
   #:+ws-child+
   #:+ws-visible+
   #:+ws-caption+
   #:+ws-border+
   #:+ws-tabstop+
   #:+ws-maximizebox+
   #:+ws-minimizebox+
   #:+ws-thickframe+
   #:+ws-sysmenu+
   #:+ws-overlappedwindow+

   ;;Window ex styles
   #:+ws-ex-left+
   #:+ws-ex-ltrreading+
   #:+ws-ex-rightscrollbar+
   #:+ws-ex-dlgmodalframe+
   #:+ws-ex-noparentnotify+
   #:+ws-ex-topmost+
   #:+ws-ex-acceptfiles+
   #:+ws-ex-transparent+
   #:+ws-ex-mdichild+
   #:+ws-ex-toolwindow+
   #:+ws-ex-windowedge+
   #:+ws-ex-clientedge+
   #:+ws-ex-contexthelp+
   #:+ws-ex-right+
   #:+ws-ex-rtlreading+
   #:+ws-ex-leftscrollbar+
   #:+ws-ex-controlparent+
   #:+ws-ex-staticedge+
   #:+ws-ex-appwindow+
   #:+ws-ex-noinheritlayout+
   #:+ws-ex-noredirectionbitmap+
   #:+ws-ex-layoutrtl+
   #:+ws-ex-composited+
   #:+ws-ex-noactivate+

   ;;Edit control types
   #:+es-left+
   #:+es-center+
   #:+es-right+

   #:+wm-null+
   #:+wm-create+
   #:+wm-destroy+
   #:+wm-move+
   #:+wm-size+
   #:+wm-activate+
   #:+wm-setfocus+
   #:+wm-killfocus+
   #:+wm-enable+
   #:+wm-setredraw+
   #:+wm-settext+
   #:+wm-gettext+
   #:+wm-gettextlength+
   #:+wm-paint+
   #:+wm-close+
   #:+wm-queryendsession+
   #:+wm-quit+
   #:+wm-queryopen+
   #:+wm-erasebkgnd+
   #:+wm-syscolorchange+
   #:+wm-endsession+
   #:+wm-systemerror+
   #:+wm-showwindow+
   #:+wm-ctlcolor+
   #:+wm-wininichange+
   #:+wm-settingchange+
   #:+wm-devmodechange+
   #:+wm-activateapp+
   #:+wm-fontchange+
   #:+wm-timechange+
   #:+wm-cancelmode+
   #:+wm-setcursor+
   #:+wm-mouseactivate+
   #:+wm-childactivate+
   #:+wm-queuesync+
   #:+wm-getminmaxinfo+
   #:+wm-painticon+
   #:+wm-iconerasebkgnd+
   #:+wm-nextdlgctl+
   #:+wm-spoolerstatus+
   #:+wm-drawitem+
   #:+wm-measureitem+
   #:+wm-deleteitem+
   #:+wm-vkeytoitem+
   #:+wm-chartoitem+
   #:+wm-setfont+
   #:+wm-getfont+
   #:+wm-sethotkey+
   #:+wm-gethotkey+
   #:+wm-querydragicon+
   #:+wm-compareitem+
   #:+wm-compacting+
   #:+wm-windowposchanging+
   #:+wm-windowposchanged+
   #:+wm-power+
   #:+wm-copydata+
   #:+wm-canceljournal+
   #:+wm-notify+
   #:+wm-inputlangchangerequest+
   #:+wm-inputlangchange+
   #:+wm-tcard+
   #:+wm-help+
   #:+wm-userchanged+
   #:+wm-notifyformat+
   #:+wm-contextmenu+
   #:+wm-stylechanging+
   #:+wm-stylechanged+
   #:+wm-displaychange+
   #:+wm-geticon+
   #:+wm-seticon+
   #:+wm-nccreate+
   #:+wm-ncdestroy+
   #:+wm-nccalcsize+
   #:+wm-nchittest+
   #:+wm-ncpaint+
   #:+wm-ncactivate+
   #:+wm-getdlgcode+
   #:+wm-syncpaint+
   #:+wm-ncmousemove+
   #:+wm-nclbuttondown+
   #:+wm-nclbuttonup+
   #:+wm-nclbuttondblclk+
   #:+wm-ncrbuttondown+
   #:+wm-ncrbuttonup+
   #:+wm-ncrbuttondblclk+
   #:+wm-ncmbuttondown+
   #:+wm-ncmbuttonup+
   #:+wm-ncmbuttondblclk+
   #:+wm-keyfirst+
   #:+wm-keydown+
   #:+wm-keyup+
   #:+wm-char+
   #:+wm-deadchar+
   #:+wm-syskeydown+
   #:+wm-syskeyup+
   #:+wm-syschar+
   #:+wm-sysdeadchar+
   #:+wm-keylast+
   #:+wm-ime_startcomposition+
   #:+wm-ime_endcomposition+
   #:+wm-ime_composition+
   #:+wm-ime_keylast+
   #:+wm-initdialog+
   #:+wm-command+
   #:+wm-syscommand+
   #:+wm-timer+
   #:+wm-hscroll+
   #:+wm-vscroll+
   #:+wm-initmenu+
   #:+wm-initmenupopup+
   #:+wm-menuselect+
   #:+wm-menuchar+
   #:+wm-enteridle+
   #:+wm-ctlcolormsgbox+
   #:+wm-ctlcoloredit+
   #:+wm-ctlcolorlistbox+
   #:+wm-ctlcolorbtn+
   #:+wm-ctlcolordlg+
   #:+wm-ctlcolorscrollbar+
   #:+wm-ctlcolorstatic+
   #:+wm-mousefirst+
   #:+wm-mousemove+
   #:+wm-lbuttondown+
   #:+wm-lbuttonup+
   #:+wm-lbuttondblclk+
   #:+wm-rbuttondown+
   #:+wm-rbuttonup+
   #:+wm-rbuttondblclk+
   #:+wm-mbuttondown+
   #:+wm-mbuttonup+
   #:+wm-mbuttondblclk+
   #:+wm-mousewheel+
   #:+wm-mousehwheel+
   #:+wm-parentnotify+
   #:+wm-entermenuloop+
   #:+wm-exitmenuloop+
   #:+wm-nextmenu+
   #:+wm-sizing+
   #:+wm-capturechanged+
   #:+wm-moving+
   #:+wm-powerbroadcast+
   #:+wm-devicechange+
   #:+wm-mdicreate+
   #:+wm-mdidestroy+
   #:+wm-mdiactivate+
   #:+wm-mdirestore+
   #:+wm-mdinext+
   #:+wm-mdimaximize+
   #:+wm-mditile+
   #:+wm-mdicascade+
   #:+wm-mdiiconarrange+
   #:+wm-mdigetactive+
   #:+wm-mdisetmenu+
   #:+wm-entersizemove+
   #:+wm-exitsizemove+
   #:+wm-dropfiles+
   #:+wm-mdirefreshmenu+
   #:+wm-ime-setcontext+
   #:+wm-ime-notify+
   #:+wm-ime-control+
   #:+wm-ime-compositionfull+
   #:+wm-ime-select+
   #:+wm-ime-char+
   #:+wm-ime-keydown+
   #:+wm-ime-keyup+
   #:+wm-mousehover+
   #:+wm-ncmouseleave+
   #:+wm-mouseleave+
   #:+wm-cut+
   #:+wm-copy+
   #:+wm-paste+
   #:+wm-clear+
   #:+wm-undo+
   #:+wm-renderformat+
   #:+wm-renderallformats+
   #:+wm-destroyclipboard+
   #:+wm-drawclipboard+
   #:+wm-paintclipboard+
   #:+wm-vscrollclipboard+
   #:+wm-sizeclipboard+
   #:+wm-askcbformatname+
   #:+wm-changecbchain+
   #:+wm-hscrollclipboard+
   #:+wm-querynewpalette+
   #:+wm-paletteischanging+
   #:+wm-palettechanged+
   #:+wm-hotkey+
   #:+wm-print+
   #:+wm-printclient+
   #:+wm-handheldfirst+
   #:+wm-handheldlast+
   #:+wm-penwinfirst+
   #:+wm-penwinlast+
   #:+wm-coalesce_first+
   #:+wm-coalesce_last+
   #:+wm-dde-first+
   #:+wm-dde-initiate+
   #:+wm-dde-terminate+
   #:+wm-dde-advise+
   #:+wm-dde-unadvise+
   #:+wm-dde-ack+
   #:+wm-dde-data+
   #:+wm-dde-request+
   #:+wm-dde-poke+
   #:+wm-dde-execute+
   #:+wm-dde-last+
   #:+wm-user+
   #:+wm-app+

   #:+time-cancel+
   #:+time-hover+
   #:+time-leave+
   #:+time-nonclient+
   #:+time-query+

   #:+cw-usedefault+

   #:+cs-vredraw+
   #:+cs-hredraw+
   #:+cs-owndc+

   #:+sw-show+

   #:+idi-application+
   #:+idc-arrow+

   #:+white-brush+
   #:+black-brush+
   #:+dc-brush+

   #:+gcl-hbrbackground+
   #:+gcl-wndproc+
   #:+gcw-atom+

   #:+gwl-wndproc+
   #:+gwl-id+
   #:+gwl-style+
   #:+gwl-userdata+

   #:+swp-nosize+
   #:+swp-nomove+
   #:+swp-nozorder+
   #:+swp-noactivate+
   #:+swp-showwindow+
   #:+swp-hidewindow+
   #:+swp-noownerzorder+
   #:+swp-noreposition+

   #:+infinite+

   #:+wait-object-0+
   #:+wait-abandoned+
   #:+wait-timeout+
   #:+wait-failed+

   #:+hwnd-top+
   #:+hwnd-bottom+
   #:+hwnd-message+
   #:+hwnd-notopmost+
   #:+hwnd-topmost+

   #:+winevent-outofcontext+
   #:+winevent-skipownthread+
   #:+winevent-skipownprocess+
   #:+winevent-incontext+

   #:+wh-mouse+
   #:+wh-mouse-ll+

   #:+delete+
   #:+read-control+
   #:+write-dac+
   #:+write-owner+
   #:+synchronize+

   #:+standard-rights-required+

   #:+standard-rights-read+
   #:+standard-rights-write+
   #:+standard-rights-execute+

   #:+standard-rights-all+
   #:+specific-rights-all+

   #:+desktop-createmenu+
   #:+desktop-createwindow+
   #:+desktop-enumerate+
   #:+desktop-hookcontrol+
   #:+desktop-journalplayback+
   #:+desktop-journalrecord+
   #:+desktop-readobjects+
   #:+desktop-switchdesktop+
   #:+desktop-writeobjects+

   #:+generic-read+
   #:+generic-write+
   #:+generic-execute+
   #:+generic-all+

   #:+file-share-delete+
   #:+file-share-read+
   #:+file-share-write+

   #:+file-attribute-archive+
   #:+file-attribute-compressed+
   #:+file-attribute-device+
   #:+file-attribute-directory+
   #:+file-attribute-encrypted+
   #:+file-attribute-hidden+
   #:+file-attribute-integrity-stream+
   #:+file-attribute-normal+
   #:+file-attribute-not-content-indexed+
   #:+file-attribute-no-scrub-data+
   #:+file-attribute-offline+
   #:+file-attribute-readonly+
   #:+file-attribute-recall-on-data-access+
   #:+file-attribute-recall-on-open+
   #:+file-attribute-reparse-point+
   #:+file-attribute-sparse-file+
   #:+file-attribute-system+
   #:+file-attribute-temporary+
   #:+file-attribute-virtual+

   #:+file-flag-backup-semantics+
   #:+file-flag-delete-on-close+
   #:+file-flag-no-buffering+
   #:+file-flag-open-no-recall+
   #:+file-flag-open-reparse-point+
   #:+file-flag-overlapped+
   #:+file-flag-posix-semantics+
   #:+file-flag-random-access+
   #:+file-flag-session-aware+
   #:+file-flag-sequential-scan+
   #:+file-flag-write-through+

   #:+movefile-replace-existing+
   #:+movefile-copy-allowed+
   #:+movefile-delay-until-reboot+
   #:+movefile-write-through+
   #:+movefile-create-hardlink+
   #:+movefile-fail-if-not-trackable+

   #:+copy-file-fail-if-exists+
   #:+copy-file-restartable+
   #:+copy-file-open-source-for-write+
   #:+copy-file-allow-decrypted-destination+
   #:+copy-file-copy-symlink+
   #:+copy-file-no-buffering+

   #:+hkey-classes-root+
   #:+hkey-current-user+
   #:+hkey-local-machine+
   #:+hkey-users+
   #:+hkey-performance-data+
   #:+hkey-current-config+
   #:+hkey-dyn-data+
   #:+hkey-performance-text+
   #:+hkey-performance-nlstext+

   #:+reg-none+
   #:+reg-sz+
   #:+reg-expand-sz+
   #:+reg-binary+
   #:+reg-dword+
   #:+reg-dword-little-endian+
   #:+reg-dword-big-endian+
   #:+reg-link+
   #:+reg-multi-sz+
   #:+reg-resource-list+
   #:+reg-full-resource-descriptor+
   #:+reg-resource-requirements-list+
   #:+reg-qword+
   #:+reg-qword-little-endian+

   #:+rrf-rt-any+
   #:+rrf-rt-dword+
   #:+rrf-rt-qword+
   #:+rrf-rt-reg-binary+
   #:+rrf-rt-reg-dword+
   #:+rrf-rt-reg-expand-sz+
   #:+rrf-rt-reg-multi-sz+
   #:+rrf-rt-reg-none+
   #:+rrf-rt-reg-qword+
   #:+rrf-rt-reg-sz+

   #:+rrf-noexpand+
   #:+rrf-zeroonfailure+
   #:+rrf-subkey-wow6464key+
   #:+rrf-subkey-wow6432key+

   #:+reg-option-reserved+
   #:+reg-option-backup-restore+
   #:+reg-option-create-link+
   #:+reg-option-non-volatile+
   #:+reg-option-volatile+
   #:+reg-option-open-link+

   #:+reg-created-new-key+
   #:+reg-opened-existing-key+

   #:+key-all-access+
   #:+key-create-link+
   #:+key-create-sub-key+
   #:+key-enumerate-sub-keys+
   #:+key-execute+
   #:+key-notify+
   #:+key-query-value+
   #:+key-read+
   #:+key-set-value+
   #:+key-wow64-32key+
   #:+key-wow64-64key+
   #:+key-write+

   #:+color-3ddkshadow+
   #:+color-3dface+
   #:+color-3dhighlight+
   #:+color-3dhilight+
   #:+color-3dlight+
   #:+color-3dshadow+
   #:+color-activeborder+
   #:+color-activecaption+
   #:+color-appworkspace+
   #:+color-background+
   #:+color-btnface+
   #:+color-btnhighlight+
   #:+color-btnhilight+
   #:+color-btnshadow+
   #:+color-btntext+
   #:+color-captiontext+
   #:+color-desktop+
   #:+color-gradientactivecaption+
   #:+color-gradientinactivecaption+
   #:+color-graytext+
   #:+color-highlight+
   #:+color-highlighttext+
   #:+color-hotlight+
   #:+color-inactiveborder+
   #:+color-inactivecaption+
   #:+color-inactivecaptiontext+
   #:+color-infobk+
   #:+color-infotext+
   #:+color-menu+
   #:+color-menuhilight+
   #:+color-menubar+
   #:+color-menutext+
   #:+color-scrollbar+
   #:+color-window+
   #:+color-windowframe+
   #:+color-windowtext+

   #:+smto-abortifhung+
   #:+smto-block+
   #:+smto-normal+
   #:+smto-notimeoutifnothung+
   #:+smto-erroronexit+

   #:+bsf-allowsfw+
   #:+bsf-flushdisk+
   #:+bsf-forceifhung+
   #:+bsf-ignorecurrenttask+
   #:+bsf-luid+
   #:+bsf-nohang+
   #:+bsf-notimeoutifnothung+
   #:+bsf-postmessage+
   #:+bsf-returnhdesk+
   #:+bsf-query+
   #:+bsf-sendnotifymessage+

   #:+bsm-allcomponents+
   #:+bsm-alldesktops+
   #:+bsm-applications+

   #:+ismex-callback+
   #:+ismex-notify+
   #:+ismex-replied+
   #:+ismex-send+

   #:+sm-arrange+
   #:+sm-cleanboot+
   #:+sm-cmonitors+
   #:+sm-cmousebuttons+
   #:+sm-convertibleslatemode+
   #:+sm-cxborder+
   #:+sm-cxcursor+
   #:+sm-cxdlgframe+
   #:+sm-cxdoubleclk+
   #:+sm-cxdrag+
   #:+sm-cxedge+
   #:+sm-cxfixedframe+
   #:+sm-cxfocusborder+
   #:+sm-cxframe+
   #:+sm-cxfullscreen+
   #:+sm-cxhscroll+
   #:+sm-cxhthumb+
   #:+sm-cxicon+
   #:+sm-cxiconspacing+
   #:+sm-cxmaximized+
   #:+sm-cxmaxtrack+
   #:+sm-cxmenucheck+
   #:+sm-cxmenusize+
   #:+sm-cxmin+
   #:+sm-cxminimized+
   #:+sm-cxminspacing+
   #:+sm-cxmintrack+
   #:+sm-cxpaddedborder+
   #:+sm-cxscreen+
   #:+sm-cxsize+
   #:+sm-cxsizeframe+
   #:+sm-cxsmicon+
   #:+sm-cxsmsize+
   #:+sm-cxvirtualscreen+
   #:+sm-cxvscroll+
   #:+sm-cyborder+
   #:+sm-cycaption+
   #:+sm-cycursor+
   #:+sm-cydlgframe+
   #:+sm-cydoubleclk+
   #:+sm-cydrag+
   #:+sm-cyedge+
   #:+sm-cyfixedframe+
   #:+sm-cyfocusborder+
   #:+sm-cyframe+
   #:+sm-cyfullscreen+
   #:+sm-cyhscroll+
   #:+sm-cyicon+
   #:+sm-cyiconspacing+
   #:+sm-cykanjiwindow+
   #:+sm-cymaximized+
   #:+sm-cymaxtrack+
   #:+sm-cymenu+
   #:+sm-cymenucheck+
   #:+sm-cymenusize+
   #:+sm-cymin+
   #:+sm-cyminimized+
   #:+sm-cyminspacing+
   #:+sm-cymintrack+
   #:+sm-cyscreen+
   #:+sm-cysize+
   #:+sm-cysizeframe+
   #:+sm-cysmcaption+
   #:+sm-cysmicon+
   #:+sm-cysmsize+
   #:+sm-cyvirtualscreen+
   #:+sm-cyvscroll+
   #:+sm-cyvthumb+
   #:+sm-dbcsenabled+
   #:+sm-debug+
   #:+sm-digitizer+
   #:+sm-immenabled+
   #:+sm-maximumtouches+
   #:+sm-mediacenter+
   #:+sm-menudropalignment+
   #:+sm-mideastenabled+
   #:+sm-mousepresent+
   #:+sm-mousehorizontalwheelpresent+
   #:+sm-mousewheelpresent+
   #:+sm-network+
   #:+sm-penwindows+
   #:+sm-remotecontrol+
   #:+sm-remotesession+
   #:+sm-samedisplayformat+
   #:+sm-secure+
   #:+sm-serverr2+
   #:+sm-showsounds+
   #:+sm-shuttingdown+
   #:+sm-slowmachine+
   #:+sm-starter+
   #:+sm-swapbutton+
   #:+sm-systemdocked+
   #:+sm-tabletpc+
   #:+sm-xvirtualscreen+
   #:+sm-yvirtualscreen+

   #:+spi-getaccesstimeout+
   #:+spi-getaudiodescription+
   #:+spi-getclientareaanimation+
   #:+spi-getdisableoverlappedcontent+
   #:+spi-getfilterkeys+
   #:+spi-getfocusborderheight+
   #:+spi-getfocusborderwidth+
   #:+spi-gethighcontrast+
   #:+spi-getlogicaldpioverride+
   #:+spi-getmessageduration+
   #:+spi-getmouseclicklock+
   #:+spi-getmouseclicklocktime+
   #:+spi-getmousekeys+
   #:+spi-getmousesonar+
   #:+spi-getmousevanish+
   #:+spi-getscreenreader+
   #:+spi-getserialkeys+
   #:+spi-getshowsounds+
   #:+spi-getsoundsentry+
   #:+spi-getstickykeys+
   #:+spi-gettogglekeys+
   #:+spi-setaccesstimeout+
   #:+spi-setaudiodescription+
   #:+spi-setclientareaanimation+
   #:+spi-setdisableoverlappedcontent+
   #:+spi-setfilterkeys+
   #:+spi-setfocusborderheight+
   #:+spi-setfocusborderwidth+
   #:+spi-sethighcontrast+
   #:+spi-setlogicaldpioverride+
   #:+spi-setmessageduration+
   #:+spi-setmouseclicklock+
   #:+spi-setmouseclicklocktime+
   #:+spi-setmousekeys+
   #:+spi-setmousesonar+
   #:+spi-setmousevanish+
   #:+spi-setscreenreader+
   #:+spi-setserialkeys+
   #:+spi-setshowsounds+
   #:+spi-setsoundsentry+
   #:+spi-setstickykeys+
   #:+spi-settogglekeys+

   ;;;Desktop parameters
   #:+spi-getcleartype+
   #:+spi-getdeskwallpaper+
   #:+spi-getdropshadow+
   #:+spi-getflatmenu+
   #:+spi-getfontsmoothing+
   #:+spi-getfontsmoothingcontrast+
   #:+spi-getfontsmoothingorientation+
   #:+spi-getfontsmoothingtype+
   #:+spi-getworkarea+
   #:+spi-setcleartype+
   #:+spi-setcursors+
   #:+spi-setdeskpattern+
   #:+spi-setdeskwallpaper+
   #:+spi-setdropshadow+
   #:+spi-setflatmenu+
   #:+spi-setfontsmoothing+
   #:+spi-setfontsmoothingcontrast+
   #:+spi-setfontsmoothingorientation+
   #:+spi-setfontsmoothingtype+
   #:+spi-setworkarea+

   ;;;Icon parameters
   #:+spi-geticonmetrics+
   #:+spi-geticontitlelogfont+
   #:+spi-geticontitlewrap+
   #:+spi-iconhorizontalspacing+
   #:+spi-iconverticalspacing+
   #:+spi-seticonmetrics+
   #:+spi-seticons+
   #:+spi-seticontitlelogfont+
   #:+spi-seticontitlewrap+

;;Input parameters
   #:+spi-getbeep+
   #:+spi-getblocksendinputresets+
   #:+spi-getcontactvisualization+
   #:+spi-getdefaultinputlang+
   #:+spi-getgesturevisualization+
   #:+spi-getkeyboardcues+
   #:+spi-getkeyboarddelay+
   #:+spi-getkeyboardpref+
   #:+spi-getkeyboardspeed+
   #:+spi-getmouse+
   #:+spi-getmousehoverheight+
   #:+spi-getmousehovertime+
   #:+spi-getmousehoverwidth+
   #:+spi-getmousespeed+
   #:+spi-getmousetrails+
   #:+spi-getmousewheelrouting+
   #:+spi-getpenvisualization+
   #:+spi-getsnaptodefbutton+
   #:+spi-getsystemlanguagebar+
   #:+spi-getthreadlocalinputsettings+
   #:+spi-getwheelscrollchars+
   #:+spi-getwheelscrolllines+
   #:+spi-setbeep+
   #:+spi-setblocksendinputresets+
   #:+spi-setcontactvisualization+
   #:+spi-setdefaultinputlang+
   #:+spi-setdoubleclicktime+
   #:+spi-setdoubleclkheight+
   #:+spi-setdoubleclkwidth+
   #:+spi-setgesturevisualization+
   #:+spi-setkeyboardcues+
   #:+spi-setkeyboarddelay+
   #:+spi-setkeyboardpref+
   #:+spi-setkeyboardspeed+
   #:+spi-setlangtoggle+
   #:+spi-setmouse+
   #:+spi-setmousebuttonswap+
   #:+spi-setmousehoverheight+
   #:+spi-setmousehovertime+
   #:+spi-setmousehoverwidth+
   #:+spi-setmousespeed+
   #:+spi-setmousetrails+
   #:+spi-setmousewheelrouting+
   #:+spi-setpenvisualization+
   #:+spi-setsnaptodefbutton+
   #:+spi-setsystemlanguagebar+
   #:+spi-setthreadlocalinputsettings+
   #:+spi-setwheelscrollchars+
   #:+spi-setwheelscrolllines+

   ;;;Menu parameters
   #:+spi-getmenudropalignment+
   #:+spi-getmenufade+
   #:+spi-getmenushowdelay+
   #:+spi-setmenudropalignment+
   #:+spi-setmenufade+
   #:+spi-setmenushowdelay+

   ;;;Power parameters
   #:+spi-getlowpoweractive+
   #:+spi-getlowpowertimeout+
   #:+spi-getpoweroffactive+
   #:+spi-getpowerofftimeout+
   #:+spi-setlowpoweractive+
   #:+spi-setlowpowertimeout+
   #:+spi-setpoweroffactive+
   #:+spi-setpowerofftimeout+

   ;;;Screen saver parameters
   #:+spi-getscreensaveactive+
   #:+spi-getscreensaverrunning+
   #:+spi-getscreensavesecure+
   #:+spi-getscreensavetimeout+
   #:+spi-setscreensaveactive+
   #:+spi-setscreensavesecure+
   #:+spi-setscreensavetimeout+

   ;;;Time-out parameters for applications/services
   #:+spi-gethungapptimeout+
   #:+spi-getwaittokilltimeout+
   #:+spi-getwaittokillservicetimeout+
   #:+spi-sethungapptimeout+
   #:+spi-setwaittokilltimeout+
   #:+spi-setwaittokillservicetimeout+

   ;;;UI effects parameters
   #:+spi-getcomboboxanimation+
   #:+spi-getcursorshadow+
   #:+spi-getgradientcaptions+
   #:+spi-gethottracking+
   #:+spi-getlistboxsmoothscrolling+
   #:+spi-getmenuanimation+
   #:+spi-getmenuunderlines+
   #:+spi-getselectionfade+
   #:+spi-gettooltipanimation+
   #:+spi-gettooltipfade+
   #:+spi-getuieffects+
   #:+spi-setcomboboxanimation+
   #:+spi-setcursorshadow+
   #:+spi-setgradientcaptions+
   #:+spi-sethottracking+
   #:+spi-setlistboxsmoothscrolling+
   #:+spi-setmenuanimation+
   #:+spi-setmenuunderlines+
   #:+spi-setselectionfade+
   #:+spi-settooltipanimation+
   #:+spi-settooltipfade+
   #:+spi-setuieffects+

   ;;;Window parameters
   #:+spi-getactivewindowtracking+
   #:+spi-getactivewndtrkzorder+
   #:+spi-getactivewndtrktimeout+
   #:+spi-getanimation+
   #:+spi-getborder+
   #:+spi-getcaretwidth+
   #:+spi-getdockmoving+
   #:+spi-getdragfrommaximize+
   #:+spi-getdragfullwindows+
   #:+spi-getforegroundflashcount+
   #:+spi-getforegroundlocktimeout+
   #:+spi-getminimizedmetrics+
   #:+spi-getmousedockthreshold+
   #:+spi-getmousedragoutthreshold+
   #:+spi-getmousesidemovethreshold+
   #:+spi-getnonclientmetrics+
   #:+spi-getpendockthreshold+
   #:+spi-getpendragoutthreshold+
   #:+spi-getpensidemovethreshold+
   #:+spi-getshowimeui+
   #:+spi-getsnapsizing+
   #:+spi-getwinarranging+
   #:+spi-setactivewindowtracking+
   #:+spi-setactivewndtrkzorder+
   #:+spi-setactivewndtrktimeout+
   #:+spi-setanimation+
   #:+spi-setborder+
   #:+spi-setcaretwidth+
   #:+spi-setdockmoving+
   #:+spi-setdragfrommaximize+
   #:+spi-setdragfullwindows+
   #:+spi-setdragheight+
   #:+spi-setdragwidth+
   #:+spi-setforegroundflashcount+
   #:+spi-setforegroundlocktimeout+
   #:+spi-setminimizedmetrics+
   #:+spi-setmousedockthreshold+
   #:+spi-setmousedragoutthreshold+
   #:+spi-setmousesidemovethreshold+
   #:+spi-setnonclientmetrics+
   #:+spi-setpendockthreshold+
   #:+spi-setpendragoutthreshold+
   #:+spi-setpensidemovethreshold+
   #:+spi-setshowimeui+
   #:+spi-setsnapsizing+
   #:+spi-setwinarranging+

   #:+spif-updateinifile+
   #:+spif-sendchange+
   #:+spif-sendwininichange+

   #:+lf-facesize+

   #:+anysize-array+

   #:+digcf-default+
   #:+digcf-present+
   #:+digcf-allclasses+
   #:+digcf-profile+
   #:+digcf-deviceinterface+
   #:+digcf-interfacedevice+

   #:+error-success+
   #:+no-error+
   #:+error-invalid-function+
   #:+error-file-not-found+
   #:+error-path-not-found+
   #:+error-too-many-open-files+
   #:+error-access-denied+
   #:+error-invalid-handle+
   #:+error-arena-trashed+
   #:+error-not-enough-memory+
   #:+error-invalid-block+
   #:+error-bad-environment+
   #:+error-bad-format+
   #:+error-invalid-access+
   #:+error-invalid-data+
   #:+error-outofmemory+
   #:+error-invalid-drive+
   #:+error-current-directory+
   #:+error-not-same-device+
   #:+error-no-more-files+
   #:+error-write-protect+
   #:+error-bad-unit+
   #:+error-not-ready+
   #:+error-bad-command+
   #:+error-crc+
   #:+error-bad-length+
   #:+error-seek+
   #:+error-not-dos-disk+
   #:+error-sector-not-found+
   #:+error-out-of-paper+
   #:+error-write-fault+
   #:+error-read-fault+
   #:+error-gen-failure+
   #:+error-sharing-violation+
   #:+error-lock-violation+
   #:+error-wrong-disk+
   #:+error-sharing-buffer-exceeded+
   #:+error-handle-eof+
   #:+error-handle-disk-full+
   #:+error-not-supported+
   #:+error-rem-not-list+
   #:+error-dup-name+
   #:+error-bad-netpath+
   #:+error-network-busy+
   #:+error-dev-not-exist+
   #:+error-too-many-cmds+
   #:+error-adap-hdw-err+
   #:+error-bad-net-resp+
   #:+error-unexp-net-err+
   #:+error-bad-rem-adap+
   #:+error-printq-full+
   #:+error-no-spool-space+
   #:+error-print-cancelled+
   #:+error-netname-deleted+
   #:+error-network-access-denied+
   #:+error-bad-dev-type+
   #:+error-bad-net-name+
   #:+error-too-many-names+
   #:+error-too-many-sess+
   #:+error-sharing-paused+
   #:+error-req-not-accep+
   #:+error-redir-paused+
   #:+error-file-exists+
   #:+error-cannot-make+
   #:+error-fail-i24+
   #:+error-out-of-structures+
   #:+error-already-assigned+
   #:+error-invalid-password+
   #:+error-invalid-parameter+
   #:+error-net-write-fault+
   #:+error-no-proc-slots+
   #:+error-too-many-semaphores+
   #:+error-excl-sem-already-owned+
   #:+error-sem-is-set+
   #:+error-too-many-sem-requests+
   #:+error-invalid-at-interrupt-time+
   #:+error-sem-owner-died+
   #:+error-sem-user-limit+
   #:+error-disk-change+
   #:+error-drive-locked+
   #:+error-broken-pipe+
   #:+error-open-failed+
   #:+error-buffer-overflow+
   #:+error-disk-full+
   #:+error-no-more-search-handles+
   #:+error-invalid-target-handle+
   #:+error-invalid-category+
   #:+error-invalid-verify-switch+
   #:+error-bad-driver-level+
   #:+error-call-not-implemented+
   #:+error-sem-timeout+
   #:+error-insufficient-buffer+
   #:+error-invalid-name+
   #:+error-invalid-level+
   #:+error-no-volume-label+
   #:+error-mod-not-found+
   #:+error-proc-not-found+
   #:+error-wait-no-children+
   #:+error-child-not-complete+
   #:+error-direct-access-handle+
   #:+error-negative-seek+
   #:+error-seek-on-device+
   #:+error-is-join-target+
   #:+error-is-joined+
   #:+error-is-substed+
   #:+error-not-joined+
   #:+error-not-substed+
   #:+error-join-to-join+
   #:+error-subst-to-subst+
   #:+error-join-to-subst+
   #:+error-subst-to-join+
   #:+error-busy-drive+
   #:+error-same-drive+
   #:+error-dir-not-root+
   #:+error-dir-not-empty+
   #:+error-is-subst-path+
   #:+error-is-join-path+
   #:+error-path-busy+
   #:+error-is-subst-target+
   #:+error-system-trace+
   #:+error-invalid-event-count+
   #:+error-too-many-muxwaiters+
   #:+error-invalid-list-format+
   #:+error-label-too-long+
   #:+error-too-many-tcbs+
   #:+error-signal-refused+
   #:+error-discarded+
   #:+error-not-locked+
   #:+error-bad-threadid-addr+
   #:+error-bad-arguments+
   #:+error-bad-pathname+
   #:+error-signal-pending+
   #:+error-max-thrds-reached+
   #:+error-lock-failed+
   #:+error-busy+
   #:+error-cancel-violation+
   #:+error-atomic-locks-not-supported+
   #:+error-invalid-segment-number+
   #:+error-invalid-ordinal+
   #:+error-already-exists+
   #:+error-invalid-flag-number+
   #:+error-sem-not-found+
   #:+error-invalid-starting-codeseg+
   #:+error-invalid-stackseg+
   #:+error-invalid-moduletype+
   #:+error-invalid-exe-signature+
   #:+error-exe-marked-invalid+
   #:+error-bad-exe-format+
   #:+error-iterated-data-exceeds-64k+
   #:+error-invalid-minallocsize+
   #:+error-dynlink-from-invalid-ring+
   #:+error-iopl-not-enabled+
   #:+error-invalid-segdpl+
   #:+error-autodataseg-exceeds-64k+
   #:+error-ring2seg-must-be-movable+
   #:+error-reloc-chain-xeeds-seglim+
   #:+error-infloop-in-reloc-chain+
   #:+error-envvar-not-found+
   #:+error-no-signal-sent+
   #:+error-filename-exced-range+
   #:+error-ring2-stack-in-use+
   #:+error-meta-expansion-too-long+
   #:+error-invalid-signal-number+
   #:+error-thread-1-inactive+
   #:+error-locked+
   #:+error-too-many-modules+
   #:+error-nesting-not-allowed+
   #:+error-bad-pipe+
   #:+error-pipe-busy+
   #:+error-no-data+
   #:+error-pipe-not-connected+
   #:+error-more-data+
   #:+error-vc-disconnected+
   #:+error-invalid-ea-name+
   #:+error-ea-list-inconsistent+
   #:+error-no-more-items+
   #:+error-cannot-copy+
   #:+error-directory+
   #:+error-eas-didnt-fit+
   #:+error-ea-file-corrupt+
   #:+error-ea-table-full+
   #:+error-invalid-ea-handle+
   #:+error-eas-not-supported+
   #:+error-not-owner+
   #:+error-too-many-posts+
   #:+error-partial-copy+
   #:+error-mr-mid-not-found+
   #:+error-invalid-address+
   #:+error-arithmetic-overflow+
   #:+error-pipe-connected+
   #:+error-pipe-listening+
   #:+error-ea-access-denied+
   #:+error-operation-aborted+
   #:+error-io-incomplete+
   #:+error-io-pending+
   #:+error-noaccess+
   #:+error-swaperror+
   #:+error-stack-overflow+
   #:+error-invalid-message+
   #:+error-can-not-complete+
   #:+error-invalid-flags+
   #:+error-unrecognized-volume+
   #:+error-file-invalid+
   #:+error-fullscreen-mode+
   #:+error-no-token+
   #:+error-baddb+
   #:+error-badkey+
   #:+error-cantopen+
   #:+error-cantread+
   #:+error-cantwrite+
   #:+error-registry-recovered+
   #:+error-registry-corrupt+
   #:+error-registry-io-failed+
   #:+error-not-registry-file+
   #:+error-key-deleted+
   #:+error-no-log-space+
   #:+error-key-has-children+
   #:+error-child-must-be-volatile+
   #:+error-notify-enum-dir+
   #:+error-dependent-services-running+
   #:+error-invalid-service-control+
   #:+error-service-request-timeout+
   #:+error-service-no-thread+
   #:+error-service-database-locked+
   #:+error-service-already-running+
   #:+error-invalid-service-account+
   #:+error-service-disabled+
   #:+error-circular-dependency+
   #:+error-service-does-not-exist+
   #:+error-service-cannot-accept-ctrl+
   #:+error-service-not-active+
   #:+error-failed-service-controller-connect+
   #:+error-exception-in-service+
   #:+error-database-does-not-exist+
   #:+error-service-specific-error+
   #:+error-process-aborted+
   #:+error-service-dependency-fail+
   #:+error-service-logon-failed+
   #:+error-service-start-hang+
   #:+error-invalid-service-lock+
   #:+error-service-marked-for-delete+
   #:+error-service-exists+
   #:+error-already-running-lkg+
   #:+error-service-dependency-deleted+
   #:+error-boot-already-accepted+
   #:+error-service-never-started+
   #:+error-duplicate-service-name+
   #:+error-end-of-media+
   #:+error-filemark-detected+
   #:+error-beginning-of-media+
   #:+error-setmark-detected+
   #:+error-no-data-detected+
   #:+error-partition-failure+
   #:+error-invalid-block-length+
   #:+error-device-not-partitioned+
   #:+error-unable-to-lock-media+
   #:+error-unable-to-unload-media+
   #:+error-media-changed+
   #:+error-bus-reset+
   #:+error-no-media-in-drive+
   #:+error-no-unicode-translation+
   #:+error-dll-init-failed+
   #:+error-shutdown-in-progress+
   #:+error-no-shutdown-in-progress+
   #:+error-io-device+
   #:+error-serial-no-device+
   #:+error-irq-busy+
   #:+error-more-writes+
   #:+error-counter-timeout+
   #:+error-floppy-id-mark-not-found+
   #:+error-floppy-wrong-cylinder+
   #:+error-floppy-unknown-error+
   #:+error-floppy-bad-registers+
   #:+error-disk-recalibrate-failed+
   #:+error-disk-operation-failed+
   #:+error-disk-reset-failed+
   #:+error-eom-overflow+
   #:+error-not-enough-server-memory+
   #:+error-possible-deadlock+
   #:+error-mapped-alignment+
   #:+error-set-power-state-vetoed+
   #:+error-set-power-state-failed+
   #:+error-too-many-links+
   #:+error-old-win-version+
   #:+error-app-wrong-os+
   #:+error-single-instance-app+
   #:+error-rmode-app+
   #:+error-invalid-dll+
   #:+error-no-association+
   #:+error-dde-fail+
   #:+error-dll-not-found+
   #:+error-bad-username+
   #:+error-not-connected+
   #:+error-open-files+
   #:+error-active-connections+
   #:+error-device-in-use+
   #:+error-bad-device+
   #:+error-connection-unavail+
   #:+error-device-already-remembered+
   #:+error-no-net-or-bad-path+
   #:+error-bad-provider+
   #:+error-cannot-open-profile+
   #:+error-bad-profile+
   #:+error-not-container+
   #:+error-extended-error+
   #:+error-invalid-groupname+
   #:+error-invalid-computername+
   #:+error-invalid-eventname+
   #:+error-invalid-domainname+
   #:+error-invalid-servicename+
   #:+error-invalid-netname+
   #:+error-invalid-sharename+
   #:+error-invalid-passwordname+
   #:+error-invalid-messagename+
   #:+error-invalid-messagedest+
   #:+error-session-credential-conflict+
   #:+error-remote-session-limit-exceeded+
   #:+error-dup-domainname+
   #:+error-no-network+
   #:+error-cancelled+
   #:+error-user-mapped-file+
   #:+error-connection-refused+
   #:+error-graceful-disconnect+
   #:+error-address-already-associated+
   #:+error-address-not-associated+
   #:+error-connection-invalid+
   #:+error-connection-active+
   #:+error-network-unreachable+
   #:+error-host-unreachable+
   #:+error-protocol-unreachable+
   #:+error-port-unreachable+
   #:+error-request-aborted+
   #:+error-connection-aborted+
   #:+error-retry+
   #:+error-connection-count-limit+
   #:+error-login-time-restriction+
   #:+error-login-wksta-restriction+
   #:+error-incorrect-address+
   #:+error-already-registered+
   #:+error-service-not-found+
   #:+error-not-authenticated+
   #:+error-not-logged-on+
   #:+error-continue+
   #:+error-already-initialized+
   #:+error-no-more-devices+
   #:+error-not-all-assigned+
   #:+error-some-not-mapped+
   #:+error-no-quotas-for-account+
   #:+error-local-user-session-key+
   #:+error-null-lm-password+
   #:+error-unknown-revision+
   #:+error-revision-mismatch+
   #:+error-invalid-owner+
   #:+error-invalid-primary-group+
   #:+error-no-impersonation-token+
   #:+error-cant-disable-mandatory+
   #:+error-no-logon-servers+
   #:+error-no-such-logon-session+
   #:+error-no-such-privilege+
   #:+error-privilege-not-held+
   #:+error-invalid-account-name+
   #:+error-user-exists+
   #:+error-no-such-user+
   #:+error-group-exists+
   #:+error-no-such-group+
   #:+error-member-in-group+
   #:+error-member-not-in-group+
   #:+error-last-admin+
   #:+error-wrong-password+
   #:+error-ill-formed-password+
   #:+error-password-restriction+
   #:+error-logon-failure+
   #:+error-account-restriction+
   #:+error-invalid-logon-hours+
   #:+error-invalid-workstation+
   #:+error-password-expired+
   #:+error-account-disabled+
   #:+error-none-mapped+
   #:+error-too-many-luids-requested+
   #:+error-luids-exhausted+
   #:+error-invalid-sub-authority+
   #:+error-invalid-acl+
   #:+error-invalid-sid+
   #:+error-invalid-security-descr+
   #:+error-bad-inheritance-acl+
   #:+error-server-disabled+
   #:+error-server-not-disabled+
   #:+error-invalid-id-authority+
   #:+error-allotted-space-exceeded+
   #:+error-invalid-group-attributes+
   #:+error-bad-impersonation-level+
   #:+error-cant-open-anonymous+
   #:+error-bad-validation-class+
   #:+error-bad-token-type+
   #:+error-no-security-on-object+
   #:+error-cant-access-domain-info+
   #:+error-invalid-server-state+
   #:+error-invalid-domain-state+
   #:+error-invalid-domain-role+
   #:+error-no-such-domain+
   #:+error-domain-exists+
   #:+error-domain-limit-exceeded+
   #:+error-internal-db-corruption+
   #:+error-internal-error+
   #:+error-generic-not-mapped+
   #:+error-bad-descriptor-format+
   #:+error-not-logon-process+
   #:+error-logon-session-exists+
   #:+error-no-such-package+
   #:+error-bad-logon-session-state+
   #:+error-logon-session-collision+
   #:+error-invalid-logon-type+
   #:+error-cannot-impersonate+
   #:+error-rxact-invalid-state+
   #:+error-rxact-commit-failure+
   #:+error-special-account+
   #:+error-special-group+
   #:+error-special-user+
   #:+error-members-primary-group+
   #:+error-token-already-in-use+
   #:+error-no-such-alias+
   #:+error-member-not-in-alias+
   #:+error-member-in-alias+
   #:+error-alias-exists+
   #:+error-logon-not-granted+
   #:+error-too-many-secrets+
   #:+error-secret-too-long+
   #:+error-internal-db-error+
   #:+error-too-many-context-ids+
   #:+error-logon-type-not-granted+
   #:+error-nt-cross-encryption-required+
   #:+error-no-such-member+
   #:+error-invalid-member+
   #:+error-too-many-sids+
   #:+error-lm-cross-encryption-required+
   #:+error-no-inheritance+
   #:+error-file-corrupt+
   #:+error-disk-corrupt+
   #:+error-no-user-session-key+
   #:+error-license-quota-exceeded+
   #:+error-invalid-window-handle+
   #:+error-invalid-menu-handle+
   #:+error-invalid-cursor-handle+
   #:+error-invalid-accel-handle+
   #:+error-invalid-hook-handle+
   #:+error-invalid-dwp-handle+
   #:+error-tlw-with-wschild+
   #:+error-cannot-find-wnd-class+
   #:+error-window-of-other-thread+
   #:+error-hotkey-already-registered+
   #:+error-class-already-exists+
   #:+error-class-does-not-exist+
   #:+error-class-has-windows+
   #:+error-invalid-index+
   #:+error-invalid-icon-handle+
   #:+error-private-dialog-index+
   #:+error-listbox-id-not-found+
   #:+error-no-wildcard-characters+
   #:+error-clipboard-not-open+
   #:+error-hotkey-not-registered+
   #:+error-window-not-dialog+
   #:+error-control-id-not-found+
   #:+error-invalid-combobox-message+
   #:+error-window-not-combobox+
   #:+error-invalid-edit-height+
   #:+error-dc-not-found+
   #:+error-invalid-hook-filter+
   #:+error-invalid-filter-proc+
   #:+error-hook-needs-hmod+
   #:+error-global-only-hook+
   #:+error-journal-hook-set+
   #:+error-hook-not-installed+
   #:+error-invalid-lb-message+
   #:+error-setcount-on-bad-lb+
   #:+error-lb-without-tabstops+
   #:+error-destroy-object-of-other-thread+
   #:+error-child-window-menu+
   #:+error-no-system-menu+
   #:+error-invalid-msgbox-style+
   #:+error-invalid-spi-value+
   #:+error-screen-already-locked+
   #:+error-hwnds-have-diff-parent+
   #:+error-not-child-window+
   #:+error-invalid-gw-command+
   #:+error-invalid-thread-id+
   #:+error-non-mdichild-window+
   #:+error-popup-already-active+
   #:+error-no-scrollbars+
   #:+error-invalid-scrollbar-range+
   #:+error-invalid-showwin-command+
   #:+error-no-system-resources+
   #:+error-nonpaged-system-resources+
   #:+error-paged-system-resources+
   #:+error-working-set-quota+
   #:+error-pagefile-quota+
   #:+error-commitment-limit+
   #:+error-menu-item-not-found+
   #:+error-eventlog-file-corrupt+
   #:+error-eventlog-cant-start+
   #:+error-log-file-full+
   #:+error-eventlog-file-changed+
   #:+rpc-s-invalid-string-binding+
   #:+rpc-s-wrong-kind-of-binding+
   #:+rpc-s-invalid-binding+
   #:+rpc-s-protseq-not-supported+
   #:+rpc-s-invalid-rpc-protseq+
   #:+rpc-s-invalid-string-uuid+
   #:+rpc-s-invalid-endpoint-format+
   #:+rpc-s-invalid-net-addr+
   #:+rpc-s-no-endpoint-found+
   #:+rpc-s-invalid-timeout+
   #:+rpc-s-object-not-found+
   #:+rpc-s-already-registered+
   #:+rpc-s-type-already-registered+
   #:+rpc-s-already-listening+
   #:+rpc-s-no-protseqs-registered+
   #:+rpc-s-not-listening+
   #:+rpc-s-unknown-mgr-type+
   #:+rpc-s-unknown-if+
   #:+rpc-s-no-bindings+
   #:+rpc-s-no-protseqs+
   #:+rpc-s-cant-create-endpoint+
   #:+rpc-s-out-of-resources+
   #:+rpc-s-server-unavailable+
   #:+rpc-s-server-too-busy+
   #:+rpc-s-invalid-network-options+
   #:+rpc-s-no-call-active+
   #:+rpc-s-call-failed+
   #:+rpc-s-call-failed-dne+
   #:+rpc-s-protocol-error+
   #:+rpc-s-unsupported-trans-syn+
   #:+rpc-s-unsupported-type+
   #:+rpc-s-invalid-tag+
   #:+rpc-s-invalid-bound+
   #:+rpc-s-no-entry-name+
   #:+rpc-s-invalid-name-syntax+
   #:+rpc-s-unsupported-name-syntax+
   #:+rpc-s-uuid-no-address+
   #:+rpc-s-duplicate-endpoint+
   #:+rpc-s-unknown-authn-type+
   #:+rpc-s-max-calls-too-small+
   #:+rpc-s-string-too-long+
   #:+rpc-s-protseq-not-found+
   #:+rpc-s-procnum-out-of-range+
   #:+rpc-s-binding-has-no-auth+
   #:+rpc-s-unknown-authn-service+
   #:+rpc-s-unknown-authn-level+
   #:+rpc-s-invalid-auth-identity+
   #:+rpc-s-unknown-authz-service+
   #:+ept-s-invalid-entry+
   #:+ept-s-cant-perform-op+
   #:+ept-s-not-registered+
   #:+rpc-s-nothing-to-export+
   #:+rpc-s-incomplete-name+
   #:+rpc-s-invalid-vers-option+
   #:+rpc-s-no-more-members+
   #:+rpc-s-not-all-objs-unexported+
   #:+rpc-s-interface-not-found+
   #:+rpc-s-entry-already-exists+
   #:+rpc-s-entry-not-found+
   #:+rpc-s-name-service-unavailable+
   #:+rpc-s-invalid-naf-id+
   #:+rpc-s-cannot-support+
   #:+rpc-s-no-context-available+
   #:+rpc-s-internal-error+
   #:+rpc-s-zero-divide+
   #:+rpc-s-address-error+
   #:+rpc-s-fp-div-zero+
   #:+rpc-s-fp-underflow+
   #:+rpc-s-fp-overflow+
   #:+rpc-x-no-more-entries+
   #:+rpc-x-ss-char-trans-open-fail+
   #:+rpc-x-ss-char-trans-short-file+
   #:+rpc-x-ss-in-null-context+
   #:+rpc-x-ss-context-damaged+
   #:+rpc-x-ss-handles-mismatch+
   #:+rpc-x-ss-cannot-get-call-handle+
   #:+rpc-x-null-ref-pointer+
   #:+rpc-x-enum-value-out-of-range+
   #:+rpc-x-byte-count-too-small+
   #:+rpc-x-bad-stub-data+
   #:+error-invalid-user-buffer+
   #:+error-unrecognized-media+
   #:+error-no-trust-lsa-secret+
   #:+error-no-trust-sam-account+
   #:+error-trusted-domain-failure+
   #:+error-trusted-relationship-failure+
   #:+error-trust-failure+
   #:+rpc-s-call-in-progress+
   #:+error-netlogon-not-started+
   #:+error-account-expired+
   #:+error-redirector-has-open-handles+
   #:+error-printer-driver-already-installed+
   #:+error-unknown-port+
   #:+error-unknown-printer-driver+
   #:+error-unknown-printprocessor+
   #:+error-invalid-separator-file+
   #:+error-invalid-priority+
   #:+error-invalid-printer-name+
   #:+error-printer-already-exists+
   #:+error-invalid-printer-command+
   #:+error-invalid-datatype+
   #:+error-invalid-environment+
   #:+rpc-s-no-more-bindings+
   #:+error-nologon-interdomain-trust-account+
   #:+error-nologon-workstation-trust-account+
   #:+error-nologon-server-trust-account+
   #:+error-domain-trust-inconsistent+
   #:+error-server-has-open-handles+
   #:+error-resource-data-not-found+
   #:+error-resource-type-not-found+
   #:+error-resource-name-not-found+
   #:+error-resource-lang-not-found+
   #:+error-not-enough-quota+
   #:+rpc-s-no-interfaces+
   #:+rpc-s-call-cancelled+
   #:+rpc-s-binding-incomplete+
   #:+rpc-s-comm-failure+
   #:+rpc-s-unsupported-authn-level+
   #:+rpc-s-no-princ-name+
   #:+rpc-s-not-rpc-error+
   #:+rpc-s-uuid-local-only+
   #:+rpc-s-sec-pkg-error+
   #:+rpc-s-not-cancelled+
   #:+rpc-x-invalid-es-action+
   #:+rpc-x-wrong-es-version+
   #:+rpc-x-wrong-stub-version+
   #:+rpc-s-group-member-not-found+
   #:+ept-s-cant-create+
   #:+rpc-s-invalid-object+
   #:+error-invalid-time+
   #:+error-invalid-form-name+
   #:+error-invalid-form-size+
   #:+error-already-waiting+
   #:+error-printer-deleted+
   #:+error-invalid-printer-state+
   #:+error-password-must-change+
   #:+error-domain-controller-not-found+
   #:+error-account-locked-out+
   #:+error-no-browser-servers-found+
   #:+error-invalid-pixel-format+
   #:+error-bad-driver+
   #:+error-invalid-window-style+
   #:+error-metafile-not-supported+
   #:+error-transform-not-supported+
   #:+error-clipping-not-supported+
   #:+error-unknown-print-monitor+
   #:+error-printer-driver-in-use+
   #:+error-spool-file-not-found+
   #:+error-spl-no-startdoc+
   #:+error-spl-no-addjob+
   #:+error-print-processor-already-installed+
   #:+error-print-monitor-already-installed+
   #:+error-wins-internal+
   #:+error-can-not-del-local-wins+
   #:+error-static-init+
   #:+error-inc-backup+
   #:+error-full-backup+
   #:+error-rec-non-existent+
   #:+error-rpl-not-allowed+
   #:+severity-success+
   #:+severity-error+
   #:+facility-windows+
   #:+facility-storage+
   #:+facility-rpc+
   #:+facility-win32+
   #:+facility-control+
   #:+facility-null+
   #:+facility-itf+
   #:+facility-dispatch+

   #:+s-ok+
   #:+s-false+
   #:+noerror+
   #:+e-unexpected+
   #:+e-notimpl+
   #:+e-outofmemory+
   #:+e-invalidarg+
   #:+e-nointerface+
   #:+e-pointer+
   #:+e-handle+
   #:+e-abort+
   #:+e-fail+
   #:+e-accessdenied+
   #:+e-pending+
   #:+co-e-init-tls+
   #:+co-e-init-shared-allocator+
   #:+co-e-init-memory-allocator+
   #:+co-e-init-class-cache+
   #:+co-e-init-rpc-channel+
   #:+co-e-init-tls-set-channel-control+
   #:+co-e-init-tls-channel-control+
   #:+co-e-init-unaccepted-user-allocator+
   #:+co-e-init-scm-mutex-exists+
   #:+co-e-init-scm-file-mapping-exists+
   #:+co-e-init-scm-map-view-of-file+
   #:+co-e-init-scm-exec-failure+
   #:+co-e-init-only-single-threaded+
   #:+ole-e-first+
   #:+ole-e-last+
   #:+ole-s-first+
   #:+ole-s-last+
   #:+ole-e-oleverb+
   #:+ole-e-advf+
   #:+ole-e-enum-nomore+
   #:+ole-e-advisenotsupported+
   #:+ole-e-noconnection+
   #:+ole-e-notrunning+
   #:+ole-e-nocache+
   #:+ole-e-blank+
   #:+ole-e-classdiff+
   #:+ole-e-cant-getmoniker+
   #:+ole-e-cant-bindtosource+
   #:+ole-e-static+
   #:+ole-e-promptsavecancelled+
   #:+ole-e-invalidrect+
   #:+ole-e-wrongcompobj+
   #:+ole-e-invalidhwnd+
   #:+ole-e-not-inplaceactive+
   #:+ole-e-cantconvert+
   #:+ole-e-nostorage+
   #:+dv-e-formatetc+
   #:+dv-e-dvtargetdevice+
   #:+dv-e-stgmedium+
   #:+dv-e-statdata+
   #:+dv-e-lindex+
   #:+dv-e-tymed+
   #:+dv-e-clipformat+
   #:+dv-e-dvaspect+
   #:+dv-e-dvtargetdevice-size+
   #:+dv-e-noiviewobject+
   #:+dragdrop-e-first+
   #:+dragdrop-e-last+
   #:+dragdrop-s-first+
   #:+dragdrop-s-last+
   #:+dragdrop-e-notregistered+
   #:+dragdrop-e-alreadyregistered+
   #:+dragdrop-e-invalidhwnd+
   #:+classfactory-e-first+
   #:+classfactory-e-last+
   #:+classfactory-s-first+
   #:+classfactory-s-last+
   #:+class-e-noaggregation+
   #:+class-e-classnotavailable+
   #:+marshal-e-first+
   #:+marshal-e-last+
   #:+marshal-s-first+
   #:+marshal-s-last+
   #:+data-e-first+
   #:+data-e-last+
   #:+data-s-first+
   #:+data-s-last+
   #:+view-e-first+
   #:+view-e-last+
   #:+view-s-first+
   #:+view-s-last+
   #:+view-e-draw+
   #:+regdb-e-first+
   #:+regdb-e-last+
   #:+regdb-s-first+
   #:+regdb-s-last+
   #:+regdb-e-readregdb+
   #:+regdb-e-writeregdb+
   #:+regdb-e-keymissing+
   #:+regdb-e-invalidvalue+
   #:+regdb-e-classnotreg+
   #:+regdb-e-iidnotreg+
   #:+cache-e-first+
   #:+cache-e-last+
   #:+cache-s-first+
   #:+cache-s-last+
   #:+cache-e-nocache-updated+
   #:+oleobj-e-first+
   #:+oleobj-e-last+
   #:+oleobj-s-first+
   #:+oleobj-s-last+
   #:+oleobj-e-noverbs+
   #:+oleobj-e-invalidverb+
   #:+clientsite-e-first+
   #:+clientsite-e-last+
   #:+clientsite-s-first+
   #:+clientsite-s-last+
   #:+inplace-e-notundoable+
   #:+inplace-e-notoolspace+
   #:+inplace-e-first+
   #:+inplace-e-last+
   #:+inplace-s-first+
   #:+inplace-s-last+
   #:+enum-e-first+
   #:+enum-e-last+
   #:+enum-s-first+
   #:+enum-s-last+
   #:+convert10-e-first+
   #:+convert10-e-last+
   #:+convert10-s-first+
   #:+convert10-s-last+
   #:+convert10-e-olestream-get+
   #:+convert10-e-olestream-put+
   #:+convert10-e-olestream-fmt+
   #:+convert10-e-olestream-bitmap-to-dib+
   #:+convert10-e-stg-fmt+
   #:+convert10-e-stg-no-std-stream+
   #:+convert10-e-stg-dib-to-bitmap+
   #:+clipbrd-e-first+
   #:+clipbrd-e-last+
   #:+clipbrd-s-first+
   #:+clipbrd-s-last+
   #:+clipbrd-e-cant-open+
   #:+clipbrd-e-cant-empty+
   #:+clipbrd-e-cant-set+
   #:+clipbrd-e-bad-data+
   #:+clipbrd-e-cant-close+
   #:+mk-e-first+
   #:+mk-e-last+
   #:+mk-s-first+
   #:+mk-s-last+
   #:+mk-e-connectmanually+
   #:+mk-e-exceededdeadline+
   #:+mk-e-needgeneric+
   #:+mk-e-unavailable+
   #:+mk-e-syntax+
   #:+mk-e-noobject+
   #:+mk-e-invalidextension+
   #:+mk-e-intermediateinterfacenotsupported+
   #:+mk-e-notbindable+
   #:+mk-e-notbound+
   #:+mk-e-cantopenfile+
   #:+mk-e-mustbotheruser+
   #:+mk-e-noinverse+
   #:+mk-e-nostorage+
   #:+mk-e-noprefix+
   #:+mk-e-enumeration-failed+
   #:+co-e-first+
   #:+co-e-last+
   #:+co-s-first+
   #:+co-s-last+
   #:+co-e-notinitialized+
   #:+co-e-alreadyinitialized+
   #:+co-e-cantdetermineclass+
   #:+co-e-classstring+
   #:+co-e-iidstring+
   #:+co-e-appnotfound+
   #:+co-e-appsingleuse+
   #:+co-e-errorinapp+
   #:+co-e-dllnotfound+
   #:+co-e-errorindll+
   #:+co-e-wrongosforapp+
   #:+co-e-objnotreg+
   #:+co-e-objisreg+
   #:+co-e-objnotconnected+
   #:+co-e-appdidntreg+
   #:+co-e-released+
   #:+ole-s-usereg+
   #:+ole-s-static+
   #:+ole-s-mac-clipformat+
   #:+dragdrop-s-drop+
   #:+dragdrop-s-cancel+
   #:+dragdrop-s-usedefaultcursors+
   #:+data-s-sameformatetc+
   #:+view-s-already-frozen+
   #:+cache-s-formatetc-notsupported+
   #:+cache-s-samecache+
   #:+cache-s-somecaches-notupdated+
   #:+oleobj-s-invalidverb+
   #:+oleobj-s-cannot-doverb-now+
   #:+oleobj-s-invalidhwnd+
   #:+inplace-s-truncated+
   #:+convert10-s-no-presentation+
   #:+mk-s-reduced-to-self+
   #:+mk-s-me+
   #:+mk-s-him+
   #:+mk-s-us+
   #:+mk-s-monikeralreadyregistered+
   #:+co-e-class-create-failed+
   #:+co-e-scm-error+
   #:+co-e-scm-rpc-failure+
   #:+co-e-bad-path+
   #:+co-e-server-exec-failure+
   #:+co-e-objsrv-rpc-failure+
   #:+mk-e-no-normalized+
   #:+co-e-server-stopping+
   #:+mem-e-invalid-root+
   #:+mem-e-invalid-link+
   #:+mem-e-invalid-size+
   #:+disp-e-unknowninterface+
   #:+disp-e-membernotfound+
   #:+disp-e-paramnotfound+
   #:+disp-e-typemismatch+
   #:+disp-e-unknownname+
   #:+disp-e-nonamedargs+
   #:+disp-e-badvartype+
   #:+disp-e-exception+
   #:+disp-e-overflow+
   #:+disp-e-badindex+
   #:+disp-e-unknownlcid+
   #:+disp-e-arrayislocked+
   #:+disp-e-badparamcount+
   #:+disp-e-paramnotoptional+
   #:+disp-e-badcallee+
   #:+disp-e-notacollection+
   #:+type-e-buffertoosmall+
   #:+type-e-invdataread+
   #:+type-e-unsupformat+
   #:+type-e-registryaccess+
   #:+type-e-libnotregistered+
   #:+type-e-undefinedtype+
   #:+type-e-qualifiednamedisallowed+
   #:+type-e-invalidstate+
   #:+type-e-wrongtypekind+
   #:+type-e-elementnotfound+
   #:+type-e-ambiguousname+
   #:+type-e-nameconflict+
   #:+type-e-unknownlcid+
   #:+type-e-dllfunctionnotfound+
   #:+type-e-badmodulekind+
   #:+type-e-sizetoobig+
   #:+type-e-duplicateid+
   #:+type-e-invalidid+
   #:+type-e-typemismatch+
   #:+type-e-outofbounds+
   #:+type-e-ioerror+
   #:+type-e-cantcreatetmpfile+
   #:+type-e-cantloadlibrary+
   #:+type-e-inconsistentpropfuncs+
   #:+type-e-circulartype+
   #:+stg-e-invalidfunction+
   #:+stg-e-filenotfound+
   #:+stg-e-pathnotfound+
   #:+stg-e-toomanyopenfiles+
   #:+stg-e-accessdenied+
   #:+stg-e-invalidhandle+
   #:+stg-e-insufficientmemory+
   #:+stg-e-invalidpointer+
   #:+stg-e-nomorefiles+
   #:+stg-e-diskiswriteprotected+
   #:+stg-e-seekerror+
   #:+stg-e-writefault+
   #:+stg-e-readfault+
   #:+stg-e-shareviolation+
   #:+stg-e-lockviolation+
   #:+stg-e-filealreadyexists+
   #:+stg-e-invalidparameter+
   #:+stg-e-mediumfull+
   #:+stg-e-abnormalapiexit+
   #:+stg-e-invalidheader+
   #:+stg-e-invalidname+
   #:+stg-e-unknown+
   #:+stg-e-unimplementedfunction+
   #:+stg-e-invalidflag+
   #:+stg-e-inuse+
   #:+stg-e-notcurrent+
   #:+stg-e-reverted+
   #:+stg-e-cantsave+
   #:+stg-e-oldformat+
   #:+stg-e-olddll+
   #:+stg-e-sharerequired+
   #:+stg-e-notfilebasedstorage+
   #:+stg-e-extantmarshallings+
   #:+stg-s-converted+
   #:+rpc-e-call-rejected+
   #:+rpc-e-call-canceled+
   #:+rpc-e-cantpost-insendcall+
   #:+rpc-e-cantcallout-inasynccall+
   #:+rpc-e-cantcallout-inexternalcall+
   #:+rpc-e-connection-terminated+
   #:+rpc-e-server-died+
   #:+rpc-e-client-died+
   #:+rpc-e-invalid-datapacket+
   #:+rpc-e-canttransmit-call+
   #:+rpc-e-client-cantmarshal-data+
   #:+rpc-e-client-cantunmarshal-data+
   #:+rpc-e-server-cantmarshal-data+
   #:+rpc-e-server-cantunmarshal-data+
   #:+rpc-e-invalid-data+
   #:+rpc-e-invalid-parameter+
   #:+rpc-e-cantcallout-again+
   #:+rpc-e-server-died-dne+
   #:+rpc-e-sys-call-failed+
   #:+rpc-e-out-of-resources+
   #:+rpc-e-attempted-multithread+
   #:+rpc-e-not-registered+
   #:+rpc-e-fault+
   #:+rpc-e-serverfault+
   #:+rpc-e-changed-mode+
   #:+rpc-e-invalidmethod+
   #:+rpc-e-disconnected+
   #:+rpc-e-retry+
   #:+rpc-e-servercall-retrylater+
   #:+rpc-e-servercall-rejected+
   #:+rpc-e-invalid-calldata+
   #:+rpc-e-cantcallout-ininputsynccall+
   #:+rpc-e-wrong-thread+
   #:+rpc-e-thread-not-init+
   #:+rpc-e-unexpected+

   #:+nte-bad-uid+
   #:+nte-bad-hash+
   #:+nte-bad-key+
   #:+nte-bad-len+
   #:+nte-bad-data+
   #:+nte-bad-signature+
   #:+nte-bad-ver+
   #:+nte-bad-algid+
   #:+nte-bad-flags+
   #:+nte-bad-type+
   #:+nte-bad-key-state+
   #:+nte-bad-hash-state+
   #:+nte-no-key+
   #:+nte-no-memory+
   #:+nte-exists+
   #:+nte-perm+
   #:+nte-not-found+
   #:+nte-double-encrypt+
   #:+nte-bad-provider+
   #:+nte-bad-prov-type+
   #:+nte-bad-public-key+
   #:+nte-bad-keyset+
   #:+nte-prov-type-not-def+
   #:+nte-prov-type-entry-bad+
   #:+nte-keyset-not-def+
   #:+nte-keyset-entry-bad+
   #:+nte-prov-type-no-match+
   #:+nte-signature-file-bad+
   #:+nte-provider-dll-fail+
   #:+nte-prov-dll-not-found+
   #:+nte-bad-keyset-param+
   #:+nte-fail+
   #:+nte-sys-err+

   #:unicode-string
   #:length
   #:maximum-length
   #:buffer

   #:luid
   #:low-part
   #:high-part

   #:bsminfo
   #:size
   #:hdesk
   #:hwnd
   #:luid

   #:logpalette
   #:paletteentry
   #:paintstruct
   #:pixelformatdescriptor
   #:point
   #:rect
   #:security-attributes
   #:trackmouseevent
   #:wndclass
   #:wndclassex
   #:msg
   #:createstruct
   #:overlapped

   #:dc
   #:erase
   #:paint
   #:restore
   #:incupdate
   #:rgbreserved

   #:num-entries
   #:palette-entries

   #:red
   #:green
   #:blue

   #:x
   #:y

   #:left
   #:top
   #:right
   #:bottom

   #:cbsize
   #:flags
   #:hwnd
   #:hover-time
   #:style
   #:wndproc
   #:clsextra
   #:wndextra
   #:instance
   #:icon
   #:cursor
   #:background
   #:menu-name
   #:wndclass-name
   #:iconsm

   #:size
   #:version
   #:pixel-type
   #:color-bits
   #:red-bits
   #:red-shift
   #:green-bits
   #:green-shift
   #:blue-bits
   #:blue-shift
   #:alpha-bits
   #:alpha-shift
   #:accum-bits
   #:accum-red-bits
   #:accum-green-bits
   #:accum-blue-bits
   #:accum-alpha-bits
   #:depth-bits
   #:stencil-bits
   #:aux-buffers
   #:layer-type
   #:reserved
   #:layer-mask
   #:visible-mask
   #:damage-mask

   #:message
   #:wparam
   #:lparam
   #:time

   #:create-params
   #:instance
   #:menu
   #:parent
   #:cy
   #:cx
   #:name
   #:class
   #:exstyle

   #:internal
   #:internal-high
   #:offset
   #:offset-high
   #:event

   #:animationinfo
   #:size
   #:minanimate

   #:audiodescription
   #:size
   #:enabled
   #:locale

   #:minimizedmetrics
   #:size
   #:width
   #:horzgap
   #:vertgap
   #:arrange

   #:logfont
   #:height
   #:width
   #:escapement
   #:orientation
   #:weight
   #:italic
   #:underline
   #:strikeout
   #:charset
   #:outprecision
   #:clipprecision
   #:quality
   #:pitchandfamily
   #:facename

   #:nonclientmetrics
   #:size
   #:borderwidth
   #:scrollwidth
   #:scrollheight
   #:captionwidth
   #:captionheight
   #:captionfont
   #:smcaptionwidth
   #:smcaptionheight
   #:smcaptionfont
   #:menuwidth
   #:menuheight
   #:menufont
   #:statusfont
   #:messagefont
   #:paddedborderwidth

   #:guid
   #:data1
   #:data2
   #:data3
   #:data4

   #:sp-devinfo-data
   #:size
   #:class-guid
   #:dev-inst
   #:reserved

   #:sp-device-interface-data
   #:size
   #:interface-class-guid
   #:flags
   #:reserved

   #:sp-device-interface-detail-data
   #:size
   #:device-path

   #:beep
   #:begin-paint
   #:broadcast-system-message
   #:broadcast-system-message-ex
   #:call-next-hook
   #:call-window-proc
   #:cancel-io
   #:choose-pixel-format
   #:client-to-screen
   #:clip-cursor
   #:close-handle
   #:close-window
   #:copy-file
   #:copy-file-ex
   #:create-desktop
   #:create-event
   #:create-file
   #:create-mutex
   #:create-palette
   #:create-semaphore
   #:create-window-ex
   #:def-window-proc
   #:delete-object
   #:describe-pixel-format
   #:destroy-cursor
   #:destroy-window
   #:dispatch-message
   #:enable-window
   #:end-paint
   #:enum-windows
   #:find-window
   #:get-class-long
   #:get-class-long-ptr
   #:get-class-word
   #:get-client-rect
   #:get-command-line
   #:get-current-process
   #:get-current-process-id
   #:get-current-processor-number
   #:get-current-thread-id
   #:get-dc
   #:get-desktop-window
   #:get-input-state
   #:get-last-error
   #:get-message
   #:get-message-exta-info
   #:get-message-pos
   #:get-message-time
   #:get-module-handle
   #:get-overlapped-result
   #:get-parent
   #:get-pixel-format
   #:get-queue-status
   #:get-shell-window
   #:get-stock-object
   #:get-sys-color
   #:get-sys-color-brush
   #:get-system-metrics
   #:get-top-window
   #:get-window-long
   #:get-window-rect
   #:get-window-text
   #:get-window-thread-process-id
   #:in-send-message
   #:in-send-message-ex
   #:invalidate-rect
   #:is-gui-thread
   #:is-window
   #:load-cursor
   #:load-cursor-from-file
   #:load-icon
   #:move-file
   #:move-file-ex
   #:open-event
   #:open-input-desktop
   #:peek-message
   #:post-message
   #:post-quit-message
   #:post-thread-message
   #:read-file
   #:realize-palette
   #:reg-close-key
   #:reg-create-key
   #:reg-create-key-ex
   #:reg-delete-key
   #:reg-delete-key-ex
   #:reg-delete-tree
   #:reg-get-value
   #:reg-open-key
   #:reg-open-key-ex
   #:reg-query-value
   #:reg-query-value-ex
   #:reg-set-value
   #:reg-set-value-ex
   #:register-class
   #:register-class-ex
   #:register-window-message
   #:release-dc
   #:reply-message
   #:reset-event
   #:resize-palette
   #:rgb
   #:select-palette
   #:send-message
   #:send-message-callback
   #:send-message-timeout
   #:send-notify-message
   #:set-class-long
   #:set-class-long-ptr
   #:set-class-word
   #:set-cursor
   #:set-cursor-pos
   #:set-event
   #:set-foreground-window
   #:set-layered-window-attributes
   #:set-message-extra-info
   #:set-parent
   #:set-pixel-format
   #:set-sys-colors
   #:set-win-event-hook
   #:set-window-long
   #:set-window-pos
   #:set-window-text
   #:set-windows-hook-ex
   #:setup-di-destroy-device-info-list
   #:setup-di-enum-device-interface
   #:setup-di-get-class-devs
   #:setup-di-get-device-interface-detail
   #:show-cursor
   #:show-window
   #:swap-buffers
   #:switch-desktop
   #:system-parameters-info
   #:track-mouse-event
   #:translate-message
   #:unregister-class
   #:update-window
   #:validate-rect
   #:wait-for-single-object
   #:wgl-create-context
   #:wgl-delete-context
   #:wgl-make-current
   #:window-from-point
   #:write-file))
